### PR TITLE
lua: ensure directories have trailing slash

### PR DESCRIPTION
**Pull request by squat**
Currently, when autocompleting a file that is a directory, the text that
is actually completed in the cmdline has no trailing slash. This makes
it annoying to type file paths as the text in the label does not match
the text that is actually inserted. This commit fixes the behavior by
ensuring that inserted text always has a trailing slash.

Note: although this achieves the desired results, I'm not sure if this
approach is semantically correct; please advise.

Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

Before:
image

After:
image

### CODE REVIEW

**Comment by hrsh7th** [comment]
Hm... It's intentional behavior because if we choose `/nvim` and the line will be `/nvim/`, we can't narrow next directory without deleting trailling slash.

**Comment by squat** [comment]
Hmm interesting. I need to think about this because I'm not sure I understand the problem you describe.

From a UX perspective it's odd because we show one thing and complete another. I would say that the current behavior is also contrary to the behavior of standard Unix tools. For example, in Bash, when you tab-complete a path, directories get trailing slashes automatically and you can continue typing the subsequent part of the path.

**Comment by squat** [comment]
To help me understand the intended experience, can you describe what you are trying to achieve?
e.g. someone types `/n` -> autocompletes to `/nvim` -> user does _not_ want `nvim/` and instead narrows directory to `?`

**Comment by hrsh7th** [comment]
I've always been bad at vim's default path completion behavior.
For example, if you select `.config` after`:e ~/<Tab>`, it will be`e ~/.config/`.
If you try to narrow down the next path in this state, you will have to enter `/` again, resulting in `e ~/.config//`.

_google translated_

**Comment by squat** [comment]
:/ I'm sorry, I don't understand the example. Maybe I am misunderstanding what we are talking about with "narrow down".

Using original vim behavior:
1. `:e ~/<Tab>` completes to `:e ~/.config/` :heavy_check_mark: 
2. What's the next path you want?

**Comment by hrsh7th** [comment]
This screencast explains what I want.

https://user-images.githubusercontent.com/629908/149768912-4911e71c-6d48-4c36-9cf4-891e0345d7de.mp4

1. Select directory item
2. Press `/` to narrow next path
3. Select directory item
4. Press `/` to narrow next path
...

**Comment by squat** [comment]
ah I see now. The problem with the proposed approach is that there is no simple way to trigger the next level of autocompletion, so you have to hack around by adding+removing a character.

**Comment by hrsh7th** [comment]
Yes.
Well, we can press `<C-Space>` for it. But it's related to my habit 😅

**Comment by squat** [comment]
Got It. That makes sense to me. I guess this is kind of a subjective UX question now. I raised this issue because the current UX clashed with my own habit and my expectations from using other CLI tools like shell completion :stuck_out_tongue:

In my case, I like to use tab completion to more quickly type paths that I already know, vs to discover other paths:
1. type `.c`
2. complete to `.config/`
3. type `n`
4. completes to `.config/nvim/`
5. etc

I can't imagine a sane way to combine both of these behaviors. We could introduce a configuration option for this completion source, but I'm not sure it's worth it. We can close this issue (:

**Comment by hrsh7th** [comment]
I think this is worth adding configuration options.

By the way, I try not to introduce options as much as possible. The first reason is that maintenance becomes more difficult as the number of options increases, but the second reason is that I am not good at English so I can't think of a suitable name.

To me, `trailling_slash = true` (default) is ok to add.

**Comment by squat** [comment]
> The first reason is that maintenance becomes more difficult as the number of options increases

Agree 100%

Thanks for your patience and communication :heart:  I'll make a new PR for this option.

**Pull request closed without merging**
