### PR TITLE
Support for webpack alias @

### PR DESCRIPTION
**Pull request by kola-web**

### CODE REVIEW

**Comment by musjj** [comment]
Can you add some documentation on this new feature?

**Comment by kola-web** [comment]
Simply support webpack's @path mapping by replacing the @ character in the path with the src directory in the current directory through regular matching

**Comment by nyngwang** [comment]
@kola-web And you do not even respect the author by following their convention of using 2-spaces for 1 indentation. You used tab-char everywhere in this PR.

**Comment by kola-web** [comment]
> @kola-web您没有遵循他们使用 2 个空格进行 1 个缩进的约定。您在此 PR 中到处都使用了 tab-char。

**Pull request closed without merging**
